In [1]:
import pandas as pd
import numpy as np
pd.Series(np.arange(10))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [2]:
import pandas as pd
import numpy as np
pd.Series([6.7,3,4,5,6], index=[1,2,3,4,5])

1    6.7
2    3.0
3    4.0
4    5.0
5    6.0
dtype: float64

In [3]:
import pandas as pd
import numpy as np
dict_color = {"red":100, "blue":200, "green": 500, "yellow":1000}
color_count = pd.Series(dict_color)
color_count.index
color_count.values
color_count[2]

500

In [4]:
import pandas as pd
import numpy as np

print(np.random.randn(2,3))
pd.DataFrame(np.random.randn(2,3))


[[-1.04961567 -0.12116651  1.60532823]
 [-0.7136349   1.45720214 -0.60050348]]


0         1         2
0  0.115270  1.494038  1.674578
1 -0.458095  0.404251  0.722591

In [15]:
import pandas as pd
import numpy as np

score = np.random.randint(40, 100, (10, 5))
print(score)
score_df = pd.DataFrame(score)
print(score_df)
subjects = ["语文", "数学", "英语", "政治", "体育"]
print(score_df.shape[0])
stu = ["同学" + str(i) for i in range(score_df.shape[0])]
data = pd.DataFrame(score, columns=subjects, index=stu)
data.shape


[[53 92 70 98 64]
 [78 47 84 91 91]
 [94 86 74 89 42]
 [80 53 72 86 87]
 [62 77 54 95 75]
 [81 88 77 75 77]
 [66 95 76 81 69]
 [57 51 40 63 46]
 [59 77 87 93 58]
 [53 53 98 66 58]]
    0   1   2   3   4
0  53  92  70  98  64
1  78  47  84  91  91
2  94  86  74  89  42
3  80  53  72  86  87
4  62  77  54  95  75
5  81  88  77  75  77
6  66  95  76  81  69
7  57  51  40  63  46
8  59  77  87  93  58
9  53  53  98  66  58
10


(10, 5)

In [3]:
import pandas as np

In [4]:
a1 = np.array([1,2,3])
print(al.ndim)

NameError: name 'al' is not defined