In [4]:
import numpy as np

In [58]:
# 1.一维数组的索引和切片
a1 = np.arange(10)
# 1.1 进行索引操作
print(a1[4])
# 1.2 进行切片操作
print(a1[4:5])
# 1.3 使用步长
print(a1[::2])
# 1.4 使用负数来作为索引
print(a1[-1])

4
[4]
[0 2 4 6 8]
9


In [6]:
# 2. 多维数组
# 也是通过中括号来索引和切片，在中括号中，使用逗号进行分割
a2 = np.random.randint(0, 10, size=(4, 6))
print(a2)

[[2 0 0 5 7 8]
 [3 8 9 4 2 6]
 [8 1 3 7 7 5]
 [9 1 2 1 6 0]]


In [15]:
print(a2[0])
print(a2[1:3])
print(a2[[0,2,3]])

[2 0 0 5 7 8]
[[3 8 9 4 2 6]
 [8 1 3 7 7 5]]
[[2 0 0 5 7 8]
 [8 1 3 7 7 5]
 [9 1 2 1 6 0]]


In [20]:
print(a2[2,1])
print(a2[[1,2],[4,5]])
print(a2[1:3,4:6])
a2[:,1]

1
[2 5]
[[2 6]
 [7 5]]


array([0, 8, 1, 1])

In [21]:
a2[:,[1,3]]

array([[0, 5],
       [8, 4],
       [1, 7],
       [1, 1]])

#索引和切片总结:
1. 如果数组是一维的，索引和切片就是跟python的列表一样的。
2. 如果是多维的(都以二维为例)，那么在中括号中，给两个值，两个值是通过逗号分隔的，逗号前面及时行，
逗号后边就是列。如果中括号只有一个值，那么就是代表的是行。
3. 如果是多维数组，那么行的部分和列的部分，都是遵循一维数组的方式，可以使用整形，切片，还可以使用中括号的形式，来代表不连续的。比如a[[1,2],[3,4]]，那么返回的就是(1,3),(2,4)的两个值。

In [60]:
a2 = np.arange(24).reshape((4,6))
print(a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [61]:
a2<10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [62]:
a2[a2<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a2[a2>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [64]:
a2[(a2<15) | (a2>10)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#布尔索引总结:
1. 布尔索引是通过相同数组上的Ture还是False来进行提取的，提取的条件可以有多个，那么如果有多个，可以使用&
来代表且，如果有对个条件，那么每个条件要使用圆括号括起来。